CREATE TABLE BRANCH (
  B_ID INT DEFAULT '0' NOT NULL,
  B_BALANCE INT DEFAULT NULL,
  B_FILLER VARCHAR(88) DEFAULT NULL,
  CONSTRAINT B_PK_TREE PRIMARY KEY (B_ID)
);

CREATE TABLE ACCOUNT (
  A_ID INTEGER DEFAULT '0' NOT NULL,
  A_B_ID INT DEFAULT '0' NOT NULL,
  A_BALANCE int DEFAULT NULL,
  A_FILLER VARCHAR(84) DEFAULT NULL,
  CONSTRAINT A_PK_TREE PRIMARY KEY (A_B_ID,A_ID)
);

CREATE TABLE TELLER (
  T_ID INTEGER DEFAULT '0' NOT NULL,
  T_B_ID INT DEFAULT '0' NOT NULL,
  T_BALANCE INT DEFAULT NULL,
  T_FILLER VARCHAR(84) DEFAULT NULL,
  CONSTRAINT T_PK_HASH PRIMARY KEY (T_B_ID,T_ID)
);

CREATE TABLE HISTORY (
  H_B_ID INT DEFAULT '0' NOT NULL,
  H_A_ID INTEGER DEFAULT NULL,
  H_T_ID INTEGER DEFAULT '0' NOT NULL,
  H_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  H_DELTA INT DEFAULT NULL,
  H_FILLER VARCHAR(22) DEFAULT NULL
);

